version: '3.1'

services:
  server:
    depends_on:
      - php
    image: nginx
    container_name: server
    networks:
      - localhost
    ports:
      - 80:80
      - 443:443
    volumes:
      - /D/Var Data/www/data/nginx:/etc/nginx/conf.d
      - /D/Var Data/www/html:/var/www/html
  php:
    image: php:7.2-fpm
    container_name: php
    networks:
      - localhost
    volumes:
      - /D/Var Data/www/html:/var/www/html
  db:
    image: mariadb
    container_name: db
    restart: always
    networks:
      - localhost
    ports:
      - 3306:3306
    volumes:
      - /D/Var Data/www/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    networks:
      - localhost
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 

networks:
  localhost:
